version: '3.8'

services:
  web-app:
    build: .
    container_name: sistema-web-nodejs
    ports:
      - "8080:3000"
    environment:
      - DATABASE_URL=postgresql://usuario:senha123@postgres:5432/sistema_db
      - NODE_ENV=production
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: banco-postgresql
    environment:
      POSTGRES_DB: sistema_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer-db
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-manager
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  portainer_data:
    driver: local

networks:
  app-network:
    driver: bridge